export const colorPresets = [
  {
    name: 'Dark Modern',
    category: 'Sombre',
    description: 'Un thème sombre moderne avec des accents violets',
    tags: ['moderne', 'professionnel', 'violet'],
    palette: {
      primary: '#9E7FFF',
      secondary: '#38bdf8',
      accent: '#f472b6',
      background: '#171717',
      surface: '#262626',
      text: '#FFFFFF',
      textSecondary: '#A3A3A3',
      border: '#2F2F2F',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    }
  },
  {
    name: 'Ocean Blue',
    category: 'Sombre',
    description: 'Inspiré par les profondeurs océaniques',
    tags: ['océan', 'bleu', 'profond'],
    palette: {
      primary: '#0ea5e9',
      secondary: '#06b6d4',
      accent: '#8b5cf6',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      textSecondary: '#94a3b8',
      border: '#334155',
      success: '#22c55e',
      warning: '#eab308',
      error: '#f87171',
    }
  },
  {
    name: 'Warm Sunset',
    category: 'Sombre',
    description: 'Couleurs chaudes d\'un coucher de soleil',
    tags: ['chaleureux', 'orange', 'coucher'],
    palette: {
      primary: '#f97316',
      secondary: '#eab308',
      accent: '#ef4444',
      background: '#1c1917',
      surface: '#292524',
      text: '#fafaf9',
      textSecondary: '#a8a29e',
      border: '#44403c',
      success: '#65a30d',
      warning: '#ca8a04',
      error: '#dc2626',
    }
  },
  {
    name: 'Forest Green',
    category: 'Sombre',
    description: 'Inspiré par la nature et les forêts',
    tags: ['nature', 'vert', 'forêt'],
    palette: {
      primary: '#22c55e',
      secondary: '#10b981',
      accent: '#84cc16',
      background: '#0f1419',
      surface: '#1f2937',
      text: '#f9fafb',
      textSecondary: '#9ca3af',
      border: '#374151',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    }
  },
  {
    name: 'Midnight Purple',
    category: 'Sombre',
    description: 'Élégance nocturne avec des tons violets',
    tags: ['élégant', 'violet', 'nuit'],
    palette: {
      primary: '#8b5cf6',
      secondary: '#a855f7',
      accent: '#ec4899',
      background: '#0c0a09',
      surface: '#1c1917',
      text: '#fafaf9',
      textSecondary: '#a8a29e',
      border: '#292524',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
    }
  },
  {
    name: 'Carbon Black',
    category: 'Sombre',
    description: 'Minimalisme avec des nuances de gris',
    tags: ['minimaliste', 'gris', 'moderne'],
    palette: {
      primary: '#6b7280',
      secondary: '#9ca3af',
      accent: '#f59e0b',
      background: '#000000',
      surface: '#111827',
      text: '#f9fafb',
      textSecondary: '#d1d5db',
      border: '#374151',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
    }
  },
  // Thèmes Clairs
  {
    name: 'Light Clean',
    category: 'Clair',
    description: 'Design épuré et lumineux',
    tags: ['épuré', 'lumineux', 'moderne'],
    palette: {
      primary: '#3b82f6',
      secondary: '#06b6d4',
      accent: '#8b5cf6',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#e2e8f0',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
    }
  },
  {
    name: 'Soft Cream',
    category: 'Clair',
    description: 'Tons crème doux et chaleureux',
    tags: ['doux', 'crème', 'chaleureux'],
    palette: {
      primary: '#d97706',
      secondary: '#dc2626',
      accent: '#7c3aed',
      background: '#fffbeb',
      surface: '#fef3c7',
      text: '#92400e',
      textSecondary: '#b45309',
      border: '#fde68a',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    }
  },
  {
    name: 'Sky Blue',
    category: 'Clair',
    description: 'Inspiré par un ciel clair',
    tags: ['ciel', 'bleu', 'aéré'],
    palette: {
      primary: '#0ea5e9',
      secondary: '#06b6d4',
      accent: '#8b5cf6',
      background: '#f0f9ff',
      surface: '#e0f2fe',
      text: '#0c4a6e',
      textSecondary: '#0369a1',
      border: '#bae6fd',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    }
  },
  {
    name: 'Rose Garden',
    category: 'Clair',
    description: 'Douceur florale avec des tons roses',
    tags: ['floral', 'rose', 'doux'],
    palette: {
      primary: '#ec4899',
      secondary: '#f472b6',
      accent: '#8b5cf6',
      background: '#fdf2f8',
      surface: '#fce7f3',
      text: '#831843',
      textSecondary: '#be185d',
      border: '#f9a8d4',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    }
  },
  // Thèmes Colorés
  {
    name: 'Neon Cyber',
    category: 'Coloré',
    description: 'Ambiance cyberpunk avec des néons',
    tags: ['cyberpunk', 'néon', 'futuriste'],
    palette: {
      primary: '#00ff88',
      secondary: '#ff0080',
      accent: '#00d4ff',
      background: '#0a0a0a',
      surface: '#1a1a2e',
      text: '#00ff88',
      textSecondary: '#16213e',
      border: '#0f3460',
      success: '#00ff88',
      warning: '#ffaa00',
      error: '#ff0080',
    }
  },
  {
    name: 'Tropical Sunset',
    category: 'Coloré',
    description: 'Couleurs vives d\'un coucher de soleil tropical',
    tags: ['tropical', 'coucher', 'vif'],
    palette: {
      primary: '#ff6b35',
      secondary: '#f7931e',
      accent: '#c5299b',
      background: '#1a0b3d',
      surface: '#2d1b69',
      text: '#ffffff',
      textSecondary: '#b794f6',
      border: '#553c9a',
      success: '#38a169',
      warning: '#d69e2e',
      error: '#e53e3e',
    }
  },
  {
    name: 'Aurora Borealis',
    category: 'Coloré',
    description: 'Inspiré par les aurores boréales',
    tags: ['aurore', 'mystique', 'coloré'],
    palette: {
      primary: '#4ade80',
      secondary: '#06b6d4',
      accent: '#a855f7',
      background: '#0f0f23',
      surface: '#1e1e3f',
      text: '#e2e8f0',
      textSecondary: '#94a3b8',
      border: '#2d3748',
      success: '#48bb78',
      warning: '#ed8936',
      error: '#f56565',
    }
  },
  // Thèmes Pastel
  {
    name: 'Pastel Dream',
    category: 'Pastel',
    description: 'Couleurs pastel douces et apaisantes',
    tags: ['pastel', 'doux', 'apaisant'],
    palette: {
      primary: '#a78bfa',
      secondary: '#fb7185',
      accent: '#34d399',
      background: '#fefefe',
      surface: '#f8fafc',
      text: '#374151',
      textSecondary: '#6b7280',
      border: '#e5e7eb',
      success: '#6ee7b7',
      warning: '#fbbf24',
      error: '#fca5a5',
    }
  },
  {
    name: 'Mint Fresh',
    category: 'Pastel',
    description: 'Fraîcheur mentholée avec des tons verts',
    tags: ['menthe', 'frais', 'vert'],
    palette: {
      primary: '#34d399',
      secondary: '#60a5fa',
      accent: '#a78bfa',
      background: '#f0fdfa',
      surface: '#ccfbf1',
      text: '#064e3b',
      textSecondary: '#047857',
      border: '#6ee7b7',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
    }
  }
];